# Generated by Django 5.0.7 on 2024-08-02 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
        ('tasks', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default=1,
                                    on_delete=django.db.models.
                                    deletion.CASCADE,
                                    related_name='tasks',
                                    to='statuses.status'),
        ),
    ]
