# Generated by Django 5.0.7 on 2024-08-07 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0004_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_labels', to='labels.label')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_labels', to='tasks.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(related_name='tasks', through='tasks.TaskLabel', to='labels.label'),
        ),
    ]
